apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-nginx
data:
  wordpress.conf: |
    server {
      listen 80 default_server;
      server_name _;
      root /var/www/html;
      index index.php index.html;
      add_header Access-Control-Allow-Origin *;
      add_header Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PUT";
      add_header Access-Control-Allow-Headers "X-Requested-With, Content-Type, Origin, Authorization";
      location / {
        try_files $uri $uri/ /index.php?$args;
      }
      # untuk generate certbot
      location /.well-known/acme-challenge/ {
        root /var/www/html;
      }

      location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass 127.0.0.1:9000;
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-env
data:
  WORDPRESS_DB_HOST: mysql-service
  WORDPRESS_DB_USER: root
  WORDPRESS_DB_NAME: wordpress
  WORDPRESS_CONFIG_EXTRA: |
    define( 'WP_AUTO_UPDATE_CORE', true );
    define( 'DISALLOW_FILE_EDIT', true );
    # aktifkan DISALLOW_FILE_MODS jika ingin install plugin true false
    define( 'DISALLOW_FILE_MODS', false );
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-gzip-config
  namespace: default
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    
    error_log /var/log/nginx/error.log warn;
    pid /var/run/nginx.pid;
    
    events {
        worker_connections 1024;
    }
    
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
        access_log /var/log/nginx/access.log main;
        
        gzip on;
        gzip_comp_level 6;
        gzip_min_length 1000;
        gzip_types
            text/plain
            text/css
            application/javascript
            application/json
            application/xml
            text/javascript
            application/xml+rss
            application/font-woff
            application/font-woff2
            image/svg+xml;
        gzip_vary on;
        add_header Vary Accept-Encoding;
        
        include /etc/nginx/conf.d/*.conf;
    }
